### ISSUE TITLE
Black screen caused by missing texture media files.

### ISSUE THREAD

**Issue by nsshoemaker** [openglsuperbible/sb6code#21]
Several of the examples, such as alienrain and tunnel, try to load texture files from the bin/media/textures directory.  For example, alienrain line number 151

tex_alien_array = sb6::ktx::file::load("media/textures/aliens.ktx");

The textures directory and the files in it are missing in github and also missing from the zip file on the superbible website.  Without the texture files these examples just display a black screen.  Does anybody have access to these texture files?

**Comment by grahamsellers** [comment]
I just downloaded the media pack from http://www.openglsuperbible.com/example-code/. I see aliens.ktx, along with all the other texture files. Are you sure you unpacked it to the right location? Are you running the sample from the bin directory?

**Comment by nsshoemaker** [comment]
Thanks, Graham.  Looks like I missed the note on the website about downloading the media files too.  I just downloaded the media files and copied textures and objects directories to bin/media.  tunnel and alienrain working fine now.
