### ISSUE TITLE
Models are missing

### ISSUE THREAD

**Issue by lochotzke** [openglsuperbible/sb6code#4]
Many of the example look in media/objects for models. That folder does not exist though.

Can you add/upload it?

**Comment by grahamsellers** [comment]
At the end of HOWTOBUILD.txt in the repository, it says this:

Most of the samples require some media files. The media files package is a
separate download available from http://www.openglsuperbible.com and is
rougly 100MB of textures, object files and shader code. Unpack the archive
to the bin/media directory before trying to run these samples.

Thanks,

Graham

**Comment by lochotzke** [comment]
I guess I was just too eager to get started.

Thanks
André
